# Dockerfile to build oracles
# Assuming you are in the root directory (oracles):
#   docker build -t oracle-builder ./docker
#   docker run -v ${PWD}:/go/src/bitbucket.org/sweetbridge/oracles -t --name oracle-builder_1 oracle-builder
# all subsequent build should reuse the container:
#   docker container start -a oracle-builder_1

FROM buildpack-deps:jessie
LABEL name=payment-forwarder

# Install the AWS CLI
RUN apt-get update &&  \
    apt-get install -y python-pip python-dev bash sed && pip install --upgrade pip && \
    pip install awscli

WORKDIR /oracles

RUN apk add --update make git gcc libc-dev
COPY payment-forwarder /oracles
ENTRYPOINT /payment-forwarder.sh
